### ISSUE TITLE
Console warning when dialog is placed incorrectly

### ISSUE THREAD

**Issue by Garbee** [GoogleChrome/dialog-polyfill#107]
Can we fire a warning in the console if we detect the dialog is a child of an `absolute` or `relative` positioned element? Many developers get caught off-guard by this, at least within those using it for MDL. If the polyfill itself could detect and warn about this case directly then all developers would get feedback on this error and understand clearly why their code isn't working right.

**Comment by samthor** [comment]
Done in #131, as well as trying to allow the dialog to work anyway (we'll no longer put the overlay on top of the dialog).

**Comment by Garbee** [comment]
Ah nice. Thanks @samthor! I had completely forgotten to checkup on this.

**Comment by samthor** [comment]
btw, I'll push a new release soon which has this. So don't get too excited.

**Comment by Garbee** [comment]
I'm good. Just didn't want to leave the issue open since the patch has landed in `master`. :wink:
