### ISSUE TITLE
"ESC" key to close isn't an optional

### ISSUE THREAD

**Issue by codsay** [GoogleChrome/dialog-polyfill#111]
Hi everyone,

There're some dialogs that I don't want user closes them when pressing on "ESC" key.
But I don't find anyway to prevent it.

Here is what I found so far.
`dialogPolyfill.DialogManager.prototype.blockDocument = function() {
    document.body.appendChild(this.overlay);
    document.body.addEventListener('focus', this.handleFocus_, true);
    document.addEventListener('keydown', this.handleKey_);
    document.addEventListener('DOMNodeRemoved', this.handleRemove_);
  };`

Is there anyway to do it? (I don't want to remove all "keydown" handlers of document!)
Thanks in advance.

**Comment by samthor** [comment]
You should add a 'cancel' event on your dialog and call `.preventDefault()`.

[See this codepen](http://codepen.io/samthor/pen/WGNjwK).
