### ISSUE TITLE
Scroll lock

### ISSUE THREAD

**Issue by Danbardo** [GoogleChrome/dialog-polyfill#112]
This is a hard bug to reproduce, but, sometimes after closing a dialog my scroll will remain locked until I refresh the page.

Is there a way to disable the scroll lock feature?

**Comment by catwithlover** [comment]
I use the code below to prevent this issue, this method is referred to [this issue]( https://github.com/tleunen/react-mdl/issues/253 ).

```
var dialog = document.querySelector('dialog');

/* ... */

//add a event-handler to refresh layout after close event on dialog
dialog.addEventListener('close', refreshLayout);

function refreshLayout() {
    document.querySelector('body').style.overflowY = '';
    document.querySelector('body').style.overflowY = 'auto';
}
```

**Comment by samthor** [comment]
I think this is a MDL issue, not a dialog issue.
