### ISSUE TITLE
We have issue with jQuery UI draggable 

### ISSUE THREAD

**Issue by UnnikrishnanBhargavakurup** [GoogleChrome/dialog-polyfill#113]
We have a issue with jQuery UI draggable mouse pointer is getting off from the dialog element.

Could you pease see the code here: [jsfiddle](http://fiddle.jshell.net/ev3Lhr5k/)

**Comment by samthor** [comment]
This is an issue with jQuery UI, and effects the native dialog too. It's nothing to do with the polyfill.
