### ISSUE TITLE
Dialog's overlay stacks over dialog

### ISSUE THREAD

**Issue by guilhermependezza** [GoogleChrome/dialog-polyfill#116]
The contents of dialog was inaccessible because dialog's overlay were on top dialog and by passing z-index rules.

The solution I've used to get the dialog working was add a display block to _dialog_overlay class.

I'm running this on Firefox 49.0
![screenshot from 2016-10-20 15-08-54](https://cloud.githubusercontent.com/assets/3024608/19570078/26940e86-96d7-11e6-801a-f58e5450aefb.png)

**Comment by samthor** [comment]
I'm confused. The overlay should be behind the dialog, even in your example: the overlay has z-index 100000, and the dialog has 100002.

**Comment by tartinesKiller** [comment]
Same problem here, with Firefox 50. Using Chrome, no problem.

**Comment by samthor** [comment]
@tartinesKiller can you try the version at HEAD?

Also, see my earlier comment. The overlay with z-index 100k is smaller than 100k + 2.

(Chrome is moot: it has native `dialog` support).

**Comment by samthor** [comment]
& is the dialog a child of something with its own stacking context?

**Comment by tartinesKiller** [comment]
Does not change anything, same problem.
Yes, I know, and that's why it driving me mad, that's not supposed to occur
I'm using Material Design Lite, but it doesn't seems to have any z-index superior to 100k.

When trying the codepen here : http://codepen.io/Garbee/full/EPoaMj/, it just works. Maybe it's a problem with mdl ?

**Comment by vladimir-s** [comment]
@tartinesKiller Same problem.
But this is not a problem with mdl. If you move the dialog tag to the same DOM tree level as the overlay, the problem will be fixed.

**Comment by manico** [comment]
There is a similar problem in Chrome (native dialog) as it is not possible to place anything above dialog. See this example with recaptcha: https://s30.postimg.org/lz5wao3z5/recaptcha.png

Is there a solution for this?

**Comment by samthor** [comment]
@manico Dialog is in the top layer, so in the native implementation, it should be impossible to place things above it. In the polyfill, it's possible but not suggested.

**Comment by samthor** [comment]
Closing this as it's related to incorrect use of stacking context. We now warn if you're making a mistake, and also are more permissive, so incorrect usage might still work: #131
