### ISSUE TITLE
DOMNodeRemoved never disposed

### ISSUE THREAD

**Issue by hcomnetworkers** [GoogleChrome/dialog-polyfill#117]
this.dialog_.addEventListener('DOMNodeRemoved') is never disposed, causing a huge stack of listeners for every opening of a new dialog:
https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.4/dialog-polyfill.js#L236

**Comment by samthor** [comment]
Thanks, this was something from testing that slipped in. I've removed it and published 0.4.5 both in git and npm.
