### ISSUE TITLE
Modal dialog makes IE freeze

### ISSUE THREAD

**Issue by leifoolsen** [GoogleChrome/dialog-polyfill#134]
Dialog Polyfill Version:
dialog-polyfill-0.4.6

What browser(s) is this bug affecting:
IE version 11.0.9600.18537

What OS (and version) are you using?
Window 7 Enterprise SP1

What are the steps to reproduce the bug? Can you create a plunker/codepen/jsfiddle which reproduces it?
* Open the demo page: https://demo.agektmr.com/dialog/
* Click on the "Open modal dialog" button
* IE11 freezes
* Only way to terminate IE is to kill it in task manager

What is the expected behavior?
It should emulate a modal dialog

What is the actual behavior?
IE11 freezes

Any other information you believe would be useful?
dialog-polyfill-0.4.5, works as expected.

**Comment by meaku** [comment]
I can confirm this bug.

**Comment by anishbenji** [comment]
This is also happening for us. But with version **0.4.5** and **IE 11.576.14393.0**. This wasn't a problem with earlier versions of IE11. Check it out at: https://heymath.com

**Comment by jewetnitg** [comment]
I am experiencing the same problem here on 0.4.6, reverting to the version i used previously (0.4.3) resolves the issue.

**Comment by anishbenji** [comment]
We've reverted to 0.4.5 to fix the issue.

**Comment by samthor** [comment]
Apologies, I've fixed this on [0.4.7](https://github.com/GoogleChrome/dialog-polyfill/releases/tag/0.4.7). This was a bug to do with tab focusing.

**Comment by meaku** [comment]
Thanks for the quick fix :)
