### ISSUE TITLE
IE11 demo crashes browser

### ISSUE THREAD

**Issue by AltronixLinq** [GoogleChrome/dialog-polyfill#137]
Hello,

When running the demo shown here:
https://demo.agektmr.com/dialog/

Clicking on "open modal dialog" will crash browser.

I am testing IE11 on windows 7.  Let me know if need any more information.

Thanks,
-Thomas

**Comment by samthor** [comment]
@agektmr I think the demo is running 0.4.6, which had an IE11 bug. [0.4.7](https://github.com/GoogleChrome/dialog-polyfill/releases/tag/0.4.7) is out now which solve this.

**Comment by agektmr** [comment]
@samthor done: https://demo.agektmr.com/dialog/
