### ISSUE TITLE
include minified js and css in npm package

### ISSUE THREAD

**Issue by jab** [GoogleChrome/dialog-polyfill#138]
The dialog-polyfill NPM package does not currently include minified versions of the js and css.

As a result, many NPM users, and therefore users of the [unpkg.com](https://unpkg.com) CDN, pull in unminified versions of these assets into their pages. Would you consider including minified versions in the NPM package?

Thanks for your consideration and for the great work on dialog-polyfill!

**Comment by jab** [comment]
ref: https://unpkg.com/dialog-polyfill/

**Comment by samthor** [comment]
It's something I've thought about. I do it for e.g. [inert-polyfill](https://github.com/GoogleChrome/inert-polyfill), which was created much more recently.

QQ: Inert includes the minified CSS inside the JS and adds it to the page as needed. Would that be useful for `dialog`, or is that actually a pretty weird concept?

**Comment by jab** [comment]
Including the CSS in the JS sounds great to me, thanks, and glad you're amenable to this!

**Comment by jimmywarting** [comment]
There are a few lib including the css in the js, Google is doing it...

**Comment by mreinstein** [comment]
@samthor would you be open to a PR for including minified css in the js? I'm happy to take this on.

**Comment by mreinstein** [comment]
I've got a PR that injects the css into the document head, open for improvement suggestions if this is something we'd find useful.

**Comment by samthor** [comment]
@mreinstein happy to accept PR.

**Comment by mreinstein** [comment]
@samthor  this is where we left off https://github.com/GoogleChrome/dialog-polyfill/pull/180
