### ISSUE TITLE
Closing dialog does not return focus to the original element.

### ISSUE THREAD

**Issue by boykoc** [GoogleChrome/dialog-polyfill#139]
When navigating with the keyboard and closing the dialog focus is not returned to the original element that had focus before opening the dialog. This is part of the expected behavior outlined in the [WAI-ARIA working draft](https://www.w3.org/TR/wai-aria-practices/#dialog_modal). 

Is this in scope for this project and planned to be included? I'm happy to work on and submit a PR.

Could also add aria-hidden attribute on the dialog to help with accessibility although not outlined in the working draft. Other aria attributes in the draft could be done by the developer (i.e. aria-labelledby).

**Comment by samthor** [comment]
So just [mucking with this](http://codepen.io/samthor/pen/qmBodz) in native, looks like Chrome doesn't support it either - I'm not against adding it in the polyfill, just something to note.

It should be fairly easy to add it:
* on `showModal` being called, store the currently focused element
* restore it when the dialog is closed
* it could get tricky if you have multiple dialogs open and you close them in random orders - maybe you'll try to focus on something behind the top layer or in an already closed dialog

And also: we set `role="dialog"` but no other accessibility properties.

**Comment by boykoc** [comment]
Sounds good.

For the multiple dialog scenario, I think this may not be an issue.

When a dialog opens, anything outside of it should not be focusable. The only way to open another dialog would be from the current dialog since the window is inert. If a dialog opens another dialog then the original dialog should then be inert. The only way to get back to the original dialog would be to close the second dialog. This would mean closing dialogs in random order should not be possible.  Thoughts?

**Comment by samthor** [comment]
Dialogs can close for any reason, including programatically :-) hence why they can close in any order.

**Comment by boykoc** [comment]
Yeah, that's true. I'll see what I come up with for addressing that, thanks.

**Comment by boykoc** [comment]
Here's a [basic native working example](https://codepen.io/boykoco/pen/JNodGM) to help flush out the concept.

Note: Escape key hasn't been addressed here but it probably should set focus as well.

**Comment by weboverhauls** [comment]
+1 to this issue, which is a bug for any keyboard user. When dialog closes, return focus to control which opened it.

**Comment by samthor** [comment]
So on further reading, I've discovered that while the [WAI-ARIA doc](https://www.w3.org/TR/wai-aria-practices/#dialog_modal) suggests returning focus after a dialog is closed, it is unfortunately _not_ part of the [`dialog`](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element) spec itself. 

With that in mind, I won't be adding this functionality to `<dialog>`—at least not until the spec changes.

Having said that, I've written a snippet thats add this behavior and I'll soon link to it in the README. [Look at it here](https://gist.github.com/samthor/babe9fad4a65625b301ba482dad284d1)—it works with both native Chrome and the polyfilled version.
