### ISSUE TITLE
dialog.returnValue not set in Safari (including possible patch)

### ISSUE THREAD

**Issue by steffenweber** [GoogleChrome/dialog-polyfill#141]
In Safari, `document.activeElement` is set to the submitted `form` and `ev.explicitOriginalTarget` is not supported i.e. `undefined`. Therefore, the `returnValue` property is always left at its default (an empty string) and it is not possible to determine which button was clicked. Is this a known issue? I was surprised that there is no open issue and no mention in the "Limitations" section of the readme either. :smiley: 

I've found a workaround using a global `click` handler as suggested on https://stackoverflow.com/q/5721724/444959.

```diff
--- a/htdocs/js/dialog-polyfill.js
+++ b/htdocs/js/dialog-polyfill.js
@@ -614,6 +614,11 @@
    * Global form 'dialog' method handler. Closes a dialog correctly on submit
    * and possibly sets its return value.
    */
+  var clickedButton;
+  document.addEventListener('click', function(ev) {
+    clickedButton = ev.target;
+  }, false);
+
   document.addEventListener('submit', function(ev) {
     var target = ev.target;
     if (!target || !target.hasAttribute('method')) { return; }
@@ -623,17 +628,7 @@
     var dialog = findNearestDialog(/** @type {Element} */ (ev.target));
     if (!dialog) { return; }
 
-    // FIXME: The original event doesn't contain the element used to submit the
-    // form (if any). Look in some possible places.
-    var returnValue;
-    var cands = [document.activeElement, ev.explicitOriginalTarget];
-    var els = ['BUTTON', 'INPUT'];
-    cands.some(function(cand) {
-      if (cand && cand.form == ev.target && els.indexOf(cand.nodeName.toUpperCase()) != -1) {
-        returnValue = cand.value;
-        return true;
-      }
-    });
+    var returnValue = clickedButton.value;
     dialog.close(returnValue);
   }, true);
```

Maybe this could be optimized by attaching the event handler only to the `dialog` but a more elegant solution than a click event handler does not seem to exist for Safari.

**Comment by steffenweber** [comment]
Hmm, the proposed patch does not support submitting a form by other means than clicking a button. This is not a problem for simple "alert"/"confirm"-like dialogs but more complex forms might contain text fields etc which can be submitted by pressing the enter key.

Pressing the enter key always seems to trigger the first submit button. So maybe we should use the first button's value if no button in the dialog has been clicked within 100 ms before the submit event? Sounds like a hack, I'm open for other solutions.

**Comment by samthor** [comment]
Wow! I didn't know that Safari changed the `activeElement`. I've done [some research myself](https://codepen.io/samthor/pen/xrLZdR) on what Chrome does (Firefox also has a `dialog` coming soon, but I haven't tried that).

It looks like the polyfill does _more_ than the native implementation. Right now, the only way `returnValue` is set (see the demo and open the modal) is if an `input type="submit"` is used to close the dialog. Hilariously, if a `button` is used, the `returnValue` is __not changed__—this means that any previous `returnValue` will remain.

If Enter is pressed, then the first `button` or `input type="submit"` will be used to submit the form, as you say. But the same `returnValue` rules apply, as above.

(I haven't checked the spec—Chrome might be wrong here too). For now though, the fix seems pretty clear—I don't see why you'd wait 100ms though. The form is submitted, and `click` occurs reliably immediately before `submit`.

**Comment by samthor** [comment]
(And thanks for the detailed writeup)

**Comment by steffenweber** [comment]
A new patch that should solve the mentioned issue.

```patch
--- dialog-polyfill.js	2017-06-23 08:10:55.477085249 +0200
+++ dialog-polyfill.js	2017-06-23 08:11:46.599006490 +0200
@@ -39,14 +39,15 @@
   }

   /**
-   * Finds the nearest <dialog> from the passed element.
+   * Finds the closest ancestor of the passed element with specific tagName.
    *
    * @param {Element} el to search from
+   * @param {String} tagName to search for
    * @return {HTMLDialogElement} dialog found
    */
-  function findNearestDialog(el) {
+  function closest(el, tagName) {
     while (el) {
-      if (el.localName === 'dialog') {
+      if (el.localName === tagName) {
         return /** @type {HTMLDialogElement} */ (el);
       }
       el = el.parentElement;
@@ -504,7 +505,7 @@
    * @return {boolean} whether candidate is contained in top dialog
    */
   dialogPolyfill.DialogManager.prototype.containedByTopDialog_ = function(candidate) {
-    while (candidate = findNearestDialog(candidate)) {
+    while (candidate = closest(candidate, 'dialog')) {
       for (var i = 0, dpi; dpi = this.pendingDialogStack[i]; ++i) {
         if (dpi.dialog === candidate) {
           return i === 0;  // only valid if top-most
@@ -614,26 +615,30 @@
    * Global form 'dialog' method handler. Closes a dialog correctly on submit
    * and possibly sets its return value.
    */
+  document.addEventListener('click', function(ev) {
+    var target = ev.target;
+    if (!target || !(/^(BUTTON|INPUT)$/.test(target.tagName) && target.type === 'submit')) return;
+
+    var form = closest(/** @type {Element} */ (target), 'form');
+    if (!form || form.getAttribute('method') !== 'dialog') return;
+
+    var dialog = closest(/** @type {Element} */ (form), 'dialog');
+    if (!dialog) return;
+
+    dialog._clickedButton = target;
+  }, false);
+
   document.addEventListener('submit', function(ev) {
     var target = ev.target;
     if (!target || !target.hasAttribute('method')) { return; }
     if (target.getAttribute('method').toLowerCase() !== 'dialog') { return; }
     ev.preventDefault();

-    var dialog = findNearestDialog(/** @type {Element} */ (ev.target));
+    var dialog = closest(/** @type {Element} */ (ev.target), 'dialog');
     if (!dialog) { return; }

-    // FIXME: The original event doesn't contain the element used to submit the
-    // form (if any). Look in some possible places.
-    var returnValue;
-    var cands = [document.activeElement, ev.explicitOriginalTarget];
-    var els = ['BUTTON', 'INPUT'];
-    cands.some(function(cand) {
-      if (cand && cand.form == ev.target && els.indexOf(cand.nodeName.toUpperCase()) != -1) {
-        returnValue = cand.value;
-        return true;
-      }
-    });
+    var clickedButton = dialog._clickedButton || dialog.querySelector('input[type="submit"], button[type="submit"]');
+    var returnValue = clickedButton ? clickedButton.value : '';
     dialog.close(returnValue);
   }, true);
```

**Comment by samthor** [comment]
Thanks for the patch, but I took a slightly different approach in #143! (Especially as the form is available on `input.form` or `button.form`).

**Comment by steffenweber** [comment]
Thank you!

Using the `form` property is clever because then even buttons which are not descendants of a `form` element but use a `form` attribute should be handled correctly.

The merged patch does not contain code (`dialog.querySelector('input[type="submit"], button[type="submit"]')`) to use the first button as a fallback when the form is submitted by other means than clicking a button (i.e. by pressing the Enter key in a text field). It instead sets the `returnValue ` to `undefined` in this case. This differs from the native behaviour in Chrome 59. Is this intentional?

Furthermore: Assume that there are multiple dialogs (which maybe but not necessarily are shown at the same time). The first dialog contains a single submit button with value "A". The second dialog contains a text-field and a submit button (whose value doesn't matter). First, I click the button in the first dialog. It closes with `returnValue` set to `A` (which is correct). Then I submit the second form by pressing the Enter key in its text field. It, too, closes with `returnValue` set to `A` (which is wrong). This happens because the global variable `dialogPolyfill.formSubmitter` still points to the first dialog's button.

This could be solved by using a per-dialog `formSubmitter` variable or by modifying the `submit` handler to check whether `dialogPolyfill.formSubmitter` belongs to a form contained in the dialog which is being closed. But this would not solve a similar issue where a dialog containing a button and a text field is first closed by clicking the button, is then re-opened and closed again by pressing Enter in the text field. What should work in both cases is to reset `dialogPolyfill.formSubmitter` after a dialog has been closed.

**Comment by samthor** [comment]
1. When you hit Enter in a text field, your browser actually pretends to click on the first `input type="submit"` or `button` ([see spec](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission)).

2. Calling `dialog.close(undefined)` does not change the `returnValue`—if it's undefined, we leave it alone. This is as per Chrome. (And it makes sense—maybe you've set `returnValue` some special way in your code)

So because of that, some of your furthermore doesn't follow. Some of it _might_ still be an issue—e.g., if I was to click to close one dialog, and then have another close programmatically, you're right: the `formSubmitter` would still be set. But the programmatic close happens now in the replaced `submit()` method. (I believe forms can only be submitted by a click or via `submit()`).

I've added [a patch](https://github.com/GoogleChrome/dialog-polyfill/commit/5a199b4c2cf963b1bf30a5067e5b629f20e9e4cf) just in case :-)

Can you run the polyfill from HEAD and see if it solves your issue? I can do a release if it does.

**Comment by steffenweber** [comment]
First of all, please excuse the late reply. I've been on vacation.

I've taken another look at the (non-)issue and have concluced that both of my misunderstandings were a result of not knowing that browsers actually `click` the first non-disabled submit button when the user presses `Enter`. I've tested the current version of the polyfill and everything is working fine. Thank you very much! :smiley:

**Comment by samthor** [comment]
Thank you!—I learnt a bunch from solving this bug and we now have a better polyfill. I'll release a new version soon.
