### ISSUE TITLE
Use `const` and `let` instead of `var`

### ISSUE THREAD

**Issue by jhpratt** [GoogleChrome/dialog-polyfill#152]
Per [Google's style guide](https://google.github.io/styleguide/jsguide.html#features-use-const-and-let). Not really necessary, but could improve readability a little.

**Comment by samthor** [comment]
Currently the code is all ES5 (no arrow functions, too) so it can be used uncompiled in older browsers. Admittedly other polyfill projects don't follow the same approach and require compilation, but for now I don't see a reason to change.
