### ISSUE TITLE
Error with PhantomJS 2.1, with gulp and dialog-polyfill version 0.4.8 is included

### ISSUE THREAD

**Issue by Csini** [GoogleChrome/dialog-polyfill#154]
```
14 08 2017 15:08:16.018:WARN [watcher]: Pattern ".../**/*.specs.js" does not match any file.
14 08 2017 15:08:23.263:INFO [karma]: Karma v0.13.22 server started at http://lo
calhost:9876/
14 08 2017 15:08:23.268:INFO [launcher]: Starting browser PhantomJS
14 08 2017 15:08:24.945:INFO [PhantomJS 2.1.1 (Windows 7 0.0.0)]: Connected on s
ocket 0t4O_0jxljFDF5Q8AAAA with id 1834520
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'methodDescriptor.get')
  at .../tmp_libs.js:91970
PhantomJS 2.1.1 (Windows 7 0.0.0) ERROR
  TypeError: undefined is not an object (evaluating 'methodDescriptor.get')
  at .../.tmp/test/tmp_libs.js:91970
```

in that line is:
```
Line 91969:      var methodDescriptor = Object.getOwnPropertyDescriptor(HTMLFormElement.prototype, 'method');
Line 91970:      var realGet = methodDescriptor.get;
```

**Comment by Csini** [comment]
with version 0.4.7 isn't the error comming...

**Comment by samthor** [comment]
Yup, because in 0.4.8 we try to polyfill HTMLFormElement to support
`method="dialog"`. We don't do that in 0.4.7 so that will work for now.

Out of curiosity, why do you include <dialog> in PhantomJS? It's weird that
standard HTML features aren't available, like HTMLFormElement.

**Comment by Csini** [comment]
I just run a "normal" unit-test for angularjs with karma, for example:
```
describe('component: blaBlaHelper', function() {
    var vm, scope, log;

    beforeEach(module('at.blabla'));

    beforeEach(inject(function ($rootScope, _$componentController_, _$log_) {
        scope = $rootScope.$new();
        vm = _$componentController_('blaBlaHelper', {$scope: scope}, {});
        log = _$log_;
        log.reset();
    }));

    afterEach(function () {

    });

    describe('dummy', function () {
        it('vm.var to be Defined', function () {
            expect(true).toEqual(true);
            console.log('Test dummy() finished');
        });
    });
});
```

-> all the main files from my bower_components are concatenated and loaded (configured in karma-config) to be availible while the test ist running (dialog-polyfill is one of them)
-> if I run the test with Karma with Chrome, there isn't any error
-> if I run it with PhantomJS (for example to monitor it better on Jenkins) than comes the error that is described above (methodDescriptor is undefined)

**Comment by Csini** [comment]
is it a good idea to make such a change with a minor version? it destroyed my build for days...

your library was defined in my bower.json so:

```
"dependencies": {
    "dialog-polyfill": "0.4.*",
     ...
}
```

**Comment by samthor** [comment]
Looks like this is [a problem with PhantomJS](https://github.com/ariya/phantomjs/issues/12056). I'd guess that it's fixed if you upgrade it to 2.5.

I'll add a workaround anyway, but it's a stopgap.

**Comment by samthor** [comment]
Please try the version of `dialog-polyfill.js` now checked in at HEAD and let me know if it fixes the problem.

**Comment by maggo** [comment]
Same problem under iOS 9: `Object.getOwnPropertyDescriptor(HTMLFormElement.prototype, "method")` returns `undefined` and kills the dialog functionality

**Comment by samthor** [comment]
@maggo can you try the version at HEAD?

**Comment by maggo** [comment]
@samthor yep error is gone, thanks

**Comment by samthor** [comment]
I've published 0.4.9 to work around this bug. It's still a bug, as these older browsers won't correctly return `dialogMethodForm.method` as "dialog".

**Comment by maggo** [comment]
Ah, classic. Thanks for the quick fix!

**Comment by Csini** [comment]
Woow you are very quick! Thank you very much!! With Version 0.4.9 works my test again! I will check also if we can update our PhantomJS version.
