### ISSUE TITLE
Error in Firefox 55.0.3

### ISSUE THREAD

**Issue by MartinBeltrame** [GoogleChrome/dialog-polyfill#155]
After updating the browser, modal no longer shows app using the same code. Can someone reproduce bug?

Thank you!

**Comment by samthor** [comment]
Can you give a clear repro case? I've tested with Firefox 55.0.3 here on Mac and I have no problems.

**Comment by jhpratt** [comment]
Confirmed working for me in FF 55.0 on Mac and Linux

**Comment by MartinBeltrame** [comment]
It's strange because in older versions it worked correctly. But thanks for the reply. I'll check my code again.
