### ISSUE TITLE
Escape doesn't close dialog

### ISSUE THREAD

**Issue by jhpratt** [GoogleChrome/dialog-polyfill#157]
Easily replicable in Firefox on [the example page](https://demo.agektmr.com/dialog/).

**Comment by gs-akhan** [comment]
@Admin, 
Are you accepting PR for this ?

**Comment by samthor** [comment]
If you'd like to contribute a patch, we'd like to accept it :)

**Comment by gs-akhan** [comment]
I don;t think there is an issue with ESC key.

The escape doesn't work for ```dialog``` and it is correct because ``dialog``` doesn't have backdrop and user is allowed to focus on other elements. We cannot close the dialog when someone hits ESC. 

However for Modal where we have backdrop. The ESC closes it on both FF & Chrome. 

Thanks

**Comment by samthor** [comment]
Thanks for the update. I'll close this issue.
