### ISSUE TITLE
Dialog width is not properly set in MS Edge as fit-content isn't supported

### ISSUE THREAD

**Issue by JarnoVgr** [GoogleChrome/dialog-polyfill#159]
Dialog width is not properly set in MS Edge as fit-content isn't supported.

Is there a workaround available?

**Comment by Onset** [comment]
After clicking on "Show modal" in the demo on Edge 16:

![image](https://user-images.githubusercontent.com/1045362/35283804-7c766a3c-0059-11e8-9d5c-e2fce0a8ed1d.png)

**Comment by JarnoVgr** [comment]
This is a simple CSS work-around that I came up with. I know it's far from perfect, but at least it's something.

`//Workaround for Edge
dialog {
  @supports (-ms-ime-align:auto) {
    max-width: 400px;
  }
}`

**Comment by saschanaz** [comment]
fit-content as a keyword is [not in standard](https://drafts.csswg.org/css-sizing-3/#sizing-values) so we have to find some standard way to style it.

>Note: This section previously defined stretch and fit-content as keywords representing the stretch-fit size and fit-content size, respectively. These keywords have been deferred to Level 4 (along with an additional contain keyword that behaves similarly to stretch but preserves the intrinsic aspect ratio, if any) to better work out the implications in situations with indefinite available space.

[The Level 4 document](https://drafts.csswg.org/css-sizing-4/) is nearly a sketch.
