### ISSUE TITLE
Safari doesn't show alert on addEventListener(close)

### ISSUE THREAD

**Issue by tfont** [GoogleChrome/dialog-polyfill#165]
dialog.returnValue firing properly on Safari on OSX.

**Comment by samthor** [comment]
I've modified [a test](https://github.com/GoogleChrome/dialog-polyfill/commit/c41b39546489ab1d99983ecb6340a2bc87509c07) to try to check for this. Can you be more detailed as to your issue, I don't understand / can't reproduce it.
