### ISSUE TITLE
Infinite loop when shift-tabbing in a modal dialog in Internet Explorer

### ISSUE THREAD

**Issue by JessevanAssen** [GoogleChrome/dialog-polyfill#166]
When shift-tab is being pressed from within a modal dialog, the polyfill gets into an infinite loop, which completely freezes the Internet Explorer  and requiring a browser restart.

Reproduction recipe:
1. In Internet Explorer (11), navigate to https://demo.agektmr.com/dialog/#showmodal. Because IE11 doesn't support `<dialog>` natively, the polyfill will be used.
2. Click the "Open modal dialog" button in the ".showModal() API" section.
3. Press Shift + TAB. The browser will scroll to the top of the document, and become unresponsive.

The culprit is the [handleFocus_ function](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L529). If `this.forwardTab_` is `false` (which it is in case of shift-tab), it will call [`document.documentElement.focus()`](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L545). This is in turn being picked up by [`document.documentElement.addEventListener('focus', this.handleFocus_, true);`](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L475), which calls `this.handleFocus_`, resulting in an infinite loop.

Edge seems to be unaffected though, because [`document.documentElement.addEventListener('focus', this.handleFocus_, true);`](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L475) won't actually fire when shift tabbing, I suspect that's because shift-tabbing might put the focus outside of the `document.documentElement`.

To show this in action, you can replace [`document.documentElement.focus()`](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L545) by 
```js
        setTimeout(function() {
          console.log("Focusing the documentElement");
          document.documentElement.focus();
        }, 0);
```
This will fill up the console log without crashing the browser.

A possible solution could be to insert `this.forwardTab_ = undefined;` right before calling [`document.documentElement.focus()`](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L545). This is already done in [the keydown listener](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L555) or [when clicking on the overlay](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L439). 
This will result in the focus listener only firing twice: once originating from the focus shift from actually pressing the tab key, and once from the call to [`document.documentElement.focus()`](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L545). In the second call, [`if (this.forwardTab_ === undefined) { return; }  // move focus only from a tab key`](https://github.com/GoogleChrome/dialog-polyfill/blob/0.4.10/dialog-polyfill.js#L536) will kill the loop.

**Comment by samthor** [comment]
Thanks for the detailed writeup. I'll look at this soon.

**Comment by LoganDark** [comment]
_29 days ago_

**Comment by samthor** [comment]
I don't think setting `forwardTab_ = undefined` makes sense, because a user might be shift-tabbing through the page, although I suppose the dialog blocks anything else from being tabbed.

FYI we can reproduce this in Safari by adding `tabindex="0"` to the `<html>` element. IE must just have that behavior by default (and I don't have a Windows machine that handy). I'll have a fix soon.

**Comment by samthor** [comment]
Can you test the solution I've pushed in [this commit](26222dd32a9fa0495cf58fd29500f6ecdebd332c)? I'll do a release if it works for you.
