### ISSUE TITLE
data-only version without manual calls to javascript

### ISSUE THREAD

**Issue by muelli** [GoogleChrome/dialog-polyfill#167]
For my single page application which needs to run on IE11 I would appreciate a library for modals which does not require JavaScript calls but rather somehow notices that a `<dialog>` element has been created and acts accordingly. As far as I can see this is currently not possible.

**Comment by samthor** [comment]
Sorry. A lot of polyfills struggle with this issue. Fundamentally this is a huge reason to use Web Components which handle loading for you.

If this is important for you and you still (two years later...) want to support IE11, try a Web Components polyfill and a WC-based dialog.
