### ISSUE TITLE
Purpose of the .fixed class

### ISSUE THREAD

**Issue by xfra35** [GoogleChrome/dialog-polyfill#170]
There's a `.fixed` class defined in [dialog-polyfill.css](https://github.com/GoogleChrome/dialog-polyfill/blob/26222dd32a9fa0495cf58fd29500f6ecdebd332c/dialog-polyfill.css#L33), but it doesn't seem to be used anywhere in the library.

Is this class defined on purpose or is it just a remnant of some previous code?

**Comment by samthor** [comment]
It's left over from some experiment. The `<dialog>` technically loads in the viewport when you open it (so on a large page, you can scroll up/down and the dialog won't follow you), but honestly that's quite odd.

Maybe this is sort of related to what we should be doing for old IE support, just having an 'old IE/fixed/simple' class: #159

**Comment by samthor** [comment]
I've added some guidance on this in the README.
