### ISSUE TITLE
formmethod on submit button in form is not respected.

### ISSUE THREAD

**Issue by AdaRoseCannon** [GoogleChrome/dialog-polyfill#178]
Forms with an `<input type="submit" value="Confirm" formmethod="post" formaction="/sponsorship" formenctype="multipart/form-data" />` should submit the form rather than close the dialog.

Currently because of `ev.preventDefault()' in the 'submit' eventlistener it prevents the form being submitted.

Current Behaviour: Dialog closes.

Expected Behaviour: Form should be posted to the URL.

**Comment by samthor** [comment]
I've fixed this in 0.5.4; we prefer the method specified in `formmethod` on the submitter of forms.
