### ISSUE TITLE
Dialog-polyfill popup is not draggable or repositionable using mouse on Chrome/Firefox

### ISSUE THREAD

**Issue by mounikapk** [GoogleChrome/dialog-polyfill#182]
Dialog-polyfill popup is not draggable or repositionable using mouse on Chrome/Firefox-

I have used dialog-polyfill to make native dialog element work like modal on chrome and firefox. But the dialog box cannot be re positioned by dragging using mouse pointer.

Please help me if i am missing anything here.

**Comment by samthor** [comment]
`<dialog>` isn't draggable by default. We've not experimented with combining the polyfill with the HTML drag and drop API yet.
