### ISSUE TITLE
Add license disclaimer to dist files?

### ISSUE THREAD

**Issue by mohe2015** [GoogleChrome/dialog-polyfill#187]
Hi,

as far as I understand the [LICENSE](https://github.com/GoogleChrome/dialog-polyfill/blob/master/LICENSE) the user needs to add a license disclaimer to every file when serving the files from a server.

Would it the useful to do this in this repository or am I wrong?

**Comment by samthor** [comment]
Yes, we should probably include it in the dist JS. But including the LICENSE adjacent is probably fine.

**Comment by mohe2015** [comment]
Nobody cares so I think it's fine
