### ISSUE TITLE
Esc key while modal is open dismisses the modal and throws ReferenceError

### ISSUE THREAD

**Issue by paxunix** [GoogleChrome/dialog-polyfill#19]
Uncaught ReferenceError: InvalidStateError is not defined

The event dispatched at https://github.com/GoogleChrome/dialog-polyfill/blob/64a2a61673a0b3762b1c03c0a58a4e2cddd872f4/dialog-polyfill.js#L263 removes the dialog and sets open=false (but doesn't remove any background styling--that's done in close()), however when close() is called, t.open is false so it thinks close() is being called on a closed dialog and tries to throw an exception type that doesn't exist.

I haven't figured out the best way to fix that.

**Comment by cvrebert** [comment]
You're presumably referring to https://github.com/GoogleChrome/dialog-polyfill/blob/64a2a61673a0b3762b1c03c0a58a4e2cddd872f4/dialog-polyfill.js#L120
That problem appears to be fixed in `master`: https://github.com/GoogleChrome/dialog-polyfill/blob/77fcf970783d70173eee7444399f55e8e9ea4273/dialog-polyfill.js#L146

**Comment by cvrebert** [comment]
@paxunix So, can you close this?

**Comment by paxunix** [comment]
Not fixed in HEAD:

<head>
  <script src="dialog-polyfill.js"></script>
  <link rel="stylesheet" type="text/css" href="dialog-polyfill.css">
</head>
<body>
  <dialog>I'm a dialog!</dialog>
  <script>
    var dialog = document.querySelector('dialog');
    dialogPolyfill.registerDialog(dialog);
    // Now dialog acts like a native <dialog>.
    dialog.showModal();
  </script>
</body>

Hit Esc once the dialog appears, see the same "InvalidStateError: close called on closed dialog" error in console.

**Comment by cvrebert** [comment]
Ah, I overlooked the other part. Well, at least the error being thrown now actually exists...

**Comment by samthor** [comment]
This should be fixed at head now.
