### ISSUE TITLE
Firefox modal isn't

### ISSUE THREAD

**Issue by taineg** [GoogleChrome/dialog-polyfill#193]
For Firefox .showModal shows the dialog but there is nothing modal about it. I can still mouseover and click elements on the underlying page. It doesn't even appear to use .backdrop.

It would also appear the form method="dialog" is not handled, either.

For Edge the size of the dialog is ridiculous.  Kinda makes .backdrop pointless if the dialog is going to be the size of the entire window.

**Comment by taineg** [comment]
My mistake. Oddly, the above is true if dom.dialog_element.enabled is set to true for Firefox. If it is set for the default value of false then the polyfill works quite well. Hmmm.

**Comment by samthor** [comment]
I don't know the state of Firefox's native implementation. I don't think it works, but perhaps the detection code fires, so this polyfill doesn't load itself.

Edge is perhaps in a similar boat. Edg_ium_ should now natively support `<dialog>`, but older Edge and IE had problems with `-fit-content` which is used to display the dialog.

**Comment by jhackett1** [comment]
i'm having the same issues in firegox but `dom.dialog_element.enabled` is off for me.

**Comment by none23** [comment]
I'm facing the same problem using Firefox 75. Modal looks fine, but doesn't trap focus

**Comment by samthor** [comment]
so I can't repro this here with Firefox 75 on my Mac.

With the caveat that the demo page @none23 you've linked to is quite old. I'm going to ask @agektmr to take it down and I'll stop linking to it.

**Comment by samthor** [comment]
We've added new demos. This was never reproducible; please open again if the new demos still have problems!
