### ISSUE TITLE
Dialog forms don't work properly and trigger a page reload in shadow DOM

### ISSUE THREAD

**Issue by hadriann** [GoogleChrome/dialog-polyfill#195]
In Firefox and Safari, inside a shadow DOM, submitting (via a submit button) a form with method set to "dialog" (inside a dialog element) triggers a page reload instead of closing the dialog with the proper `returnValue`.

**Comment by hadriann** [comment]
This seems to happen because the `submit` event is handled globally at document level. It works well in regular DOM, as the event bubbles up. In shadow DOM, the event still bubbles up, but it doesn't propagate across the shadow DOM boundary because the `composed` property of the submit event is `false`.

**Comment by samthor** [comment]
Thanks for the report. I'll solve this by setting composed and handling it
globally.

**Comment by hadriann** [comment]
But can you override the composed flag of the native submit event?

**Comment by samthor** [comment]
I've fixed this in 0.5.4.
