### ISSUE TITLE
oncancel listener doesn't work

### ISSUE THREAD

**Issue by kippo** [GoogleChrome/dialog-polyfill#199]
The oncancel listener doesn't fire an event when the modal is cancelled through either dialog.close or using the escape key. Tested in firefox but assuming this doesn't work in either IE or Safari as well.

**Comment by samthor** [comment]
I've added this and it will release in the next version.

Technically the ordering of "on..." events is crazy—if you set an oncancel property, it gets inserted in the list of events added by `addEventListener`. I've not done this, instead just calling it first if it exists.
