### ISSUE TITLE
Is this guaranteed to appear always on top?

### ISSUE THREAD

**Issue by whatsdis** [GoogleChrome/dialog-polyfill#20]
Disappointed chrome requires the experimental flag turned on. I like the idea of <dialog> because it would ensure that it will never get hidden below elements. I am creating a chrome extension and this is important for me that the dialog always appear on top of all other elements on a given page.

**Comment by samthor** [comment]
The guarantee is only for `showModal`, as it appears in the "top layer", outside normal z-index. `show` just adds it as regular DOM.

Again, this doesn't apply to the polyfill, which just uses a "very large" value for z-index.
