### ISSUE TITLE
.backdrop vs ._dialog_overlay?

### ISSUE THREAD

**Issue by techboyg5** [GoogleChrome/dialog-polyfill#208]
Where are there two elements inserted for a modal dialog backdrop? I'd except just one.

**Comment by samthor** [comment]
The spec allows for many dialogs to be open at once.

* Each dialog has its own `.backdrop` element, which can be customized (size, color, etc)
* But `._dialog_overlay` is inserted only once at the top-level to prevent clicks on the page behind it (it's not intended to be user-customizable).

**Comment by techboyg5** [comment]
Understood.
