### ISSUE TITLE
dialogPolyfill.registerDialog and browsers with native dialog support

### ISSUE THREAD

**Issue by pierlo-upitup** [GoogleChrome/dialog-polyfill#21]
Shouldn't `dialogPolyfill.registerDialog(element)` transparently leave it to the browser when native `<dialog>` is supported?

It currently warns the user that the browser already offers support and that the polyfill may not work correctly, but still actually performing the polyfill bindings... ? (see https://github.com/GoogleChrome/dialog-polyfill/blob/master/dialog-polyfill.js#L153 )

**Comment by ThiRaBrTNK** [comment]
It seems right to me to add ```return;``` after https://github.com/GoogleChrome/dialog-polyfill/blob/master/dialog-polyfill.js#L184. @samthor, should I PR this?

**Comment by jeffutter** [comment]
This has been open for a while. Any Progress?

**Comment by samthor** [comment]
The line number has since moved - what do you want to add again?

**Comment by ThiRaBrTNK** [comment]
How about `return;` after https://github.com/GoogleChrome/dialog-polyfill/blob/master/dialog-polyfill.js#L283 ?
