### ISSUE TITLE
Safari 14.0.2 Backdrop and dialog content issue

### ISSUE THREAD

**Issue by OriginalDrTone** [GoogleChrome/dialog-polyfill#212]
Dialog body content is empty or messed up.  Transparent backdrop isn't happening at all.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/7000421/102786772-a68dc980-4365-11eb-9971-6eac8ba9783f.png">

Script error not sure if it's related:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/7000421/102786918-e48aed80-4365-11eb-87a6-62e337bd1383.png">

**Comment by samthor** [comment]
Is this related to #211, i.e., do you have the experimental element enabled?

**Comment by OriginalDrTone** [comment]
My screen shots are without the experimental feature enabled.  I had also tried it with it enabled but it didn't work as already mentioned in the referenced issue.

**Comment by samthor** [comment]
I'm not 100% sure this is the visible issue but I've just published 0.5.6 which fixes the code issue you've described. Let me know how it goes.

**Comment by JeffFlowerday** [comment]
The error is gone, thanks.  The visual issue seems to be unrelated to dialog-polyfill as I now see it happens with the experimental dialog feature enabled as well.

Again thanks!
