### ISSUE TITLE
Attach css within the script

### ISSUE THREAD

**Issue by nuxodin** [GoogleChrome/dialog-polyfill#219]
What would be the disadvantage of appending the css inside the script to the document?
It would be a much simpler approach and I don't see any disadvantages, plus a request would be saved.

I mean something like:
```js
var css =
'dialog { \
  position: absolute; \
  ... \
';
var sEl = document.createElement('style');
sEl.appendChild(document.createTextNode(css));
document.head.append(sEl);
```

**Comment by StephanBijzitter** [comment]
This would be a pain in the ass when you have a Content Security Policy set up

**Comment by samthor** [comment]
Yes, please include the CSS in whatever way suits your site best.
