### ISSUE TITLE
JavaScript error in Internet Explorer 9 (tested)

### ISSUE THREAD

**Issue by andrewjfisher** [GoogleChrome/dialog-polyfill#24]
The  call to "backdrop.classList.add('backdrop')" throws an error.

**Comment by cvrebert** [comment]
The offending code has been fixed in `master` and now uses `className` instead:
https://github.com/GoogleChrome/dialog-polyfill/blob/77fcf970783d70173eee7444399f55e8e9ea4273/dialog-polyfill.js#L369

**Comment by cvrebert** [comment]
However, one of the demos still uses `classList` in a couple places:
https://github.com/GoogleChrome/dialog-polyfill/blob/master/tests/fancy-modal-dialog.html#L244
