### ISSUE TITLE
dynamically inserted dialog not working properly

### ISSUE THREAD

**Issue by seralo** [GoogleChrome/dialog-polyfill#27]
When I insert dynamicaly HTML code that contains a form with method=dialog
ie: <dialog><form method="dialog"><button type="submit" value="no">Reject</button></form></dialog>

The form submission is not intercepted and the native browser submit is executed.

Forms with method=dialog are only filtered in the window.onload maybe forms could be filtered in the  "dialogPolyfill.registerDialog"

**Comment by samthor** [comment]
Fixed now, we install a global `submit` handler that looks for method `dialog`.
