### ISSUE TITLE
"Unable to get property 'focusFirst' of undefined or null reference" on IE11

### ISSUE THREAD

**Issue by puf** [GoogleChrome/dialog-polyfill#28]
I get this error:

> Unable to get property 'focusFirst' of undefined or null reference

on this line (currently line 406) of dialog-polyfill.js:

    dialog.removeChild(this.dialogPolyfillInfo.focusFirst);

in both my own test and https://rawgit.com/GoogleChrome/dialog-polyfill/master/tests/modal-dialog-stacking.html

**Comment by cvrebert** [comment]
@samthor Can this now be closed due to #29?

**Comment by cvrebert** [comment]
@puf Can you close this since #29 was merged?
