### ISSUE TITLE
Shouldn't focusing be done on show()?

### ISSUE THREAD

**Issue by ThiRaBrTNK** [GoogleChrome/dialog-polyfill#33]
As both [WHATWG](https://html.spec.whatwg.org/multipage/forms.html#the-dialog-element) and [W3](http://www.w3.org/html/wg/drafts/html/master/interactive-elements.html#the-dialog-element) says, dialog focusing steps should be performed both on show() and showModal() calls, but polyfill performes them only on showModal() call.

**Comment by samthor** [comment]
Note that the native Chrome implementation doesn't do this. I'll accept that it's still a bug though.

**Comment by ThiRaBrTNK** [comment]
Reported the same issue to chromium team https://code.google.com/p/chromium/issues/detail?id=565970

**Comment by mattto** [comment]
Native Chrome impl should be fixed in 48+: https://code.google.com/p/chromium/issues/detail?id=447873

**Comment by samthor** [comment]
Ok, I'll accept this as a bug and take a look!
