### ISSUE TITLE
Create a dialog element

### ISSUE THREAD

**Issue by shoman42** [GoogleChrome/dialog-polyfill#34]
Can you add `document.createElement("dialog");` to the script, some browsers don't recognize the <dialog> element when they parse the DOM.  They just make an empty <dialog> node which gets scripted, but the content follows as a sibling.

**Comment by cvrebert** [comment]
What about just using [html5shiv](https://github.com/aFarkas/html5shiv)?

**Comment by samthor** [comment]
What browsers does this effect? We only support IE9+ and other modern browsers.
