### ISSUE TITLE
Revision of what demos to provide  to users of browsers without native dialog element support may be needed. 

### ISSUE THREAD

**Issue by lozandier** [GoogleChrome/dialog-polyfill#35]
It seems the demo page provided only informs the user their browser doesn't support `dialog`, but it doesn't seem to implement the actual polypill to experience things regarding the demo like the one that can be found [here](http://demo.agektmr.com/dialog/). 

The dialog demo page I've linked to in the last paragraph may be provided to readers of the repository in addition to the one currently in the `readme.md` ( or replace the existing one ).

**Comment by samthor** [comment]
@agektmr I'm closing out old bugs. Any chance you could update your [demo site](https://demo.agektmr.com/dialog/) to include the latest version of the polyfill?

**Comment by agektmr** [comment]
@samthor Done.

**Comment by samthor** [comment]
Thanks @agektmr. You might need to update the code every now and again as I make more releases.

**Comment by agektmr** [comment]
@samthor Just ping me so I can update it.
