### ISSUE TITLE
The tops of tall dialogs are out of viewport if the dialog is taller than the viewport

### ISSUE THREAD

**Issue by edlebert** [GoogleChrome/dialog-polyfill#59]
https://html.spec.whatwg.org/multipage/forms.html#centered-alignment

The spec says that "When an element subject is placed in centered alignment mode, and when it is in that mode and has new rendering boxes created, the user agent must set up the element such that its top static position, for the purposes of calculating the used value of the 'top' property, is the value that would place the element's top margin edge as far from the top of the viewport as the element's bottom margin edge from the bottom of the viewport, if the element's height is less than the height of the viewport, and otherwise is the value that would place the element's top margin edge at the top of the viewport."

So if the dialog is taller than the viewport, the dialog should be positioned at the top of the viewport.  I opened a PR for this as well.

**Comment by samthor** [comment]
I think this was fixed a while ago, but I've added an explicit test for it.
