### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jmalonzo** [GoogleChrome/dialog-polyfill#74]
Hi @samthor! Thanks for doing this polyfill. I'm just wondering if it's possible to have a new tag/release here every now and then? The last tag was earlier this year and there have been plenty of commits since then (hence, the bower version getting pulled is pretty old). 

Thanks a lot for your time.

**Comment by samthor** [comment]
Yes! I'd love to. Actually my concern is that right now the release possibly doesn't work in IE9, but I can tag a new one.

**Comment by samthor** [comment]
Thanks for the motivation. Done!

**Comment by jmalonzo** [comment]
Awesome! Thanks again. Cheers
