### ISSUE TITLE
Open CustomEvent missing

### ISSUE THREAD

**Issue by lozandier** [GoogleChrome/dialog-polyfill#89]
For some reason, the open event is suddenly missing for the `open` & `showModal` methods; are there particular reason for its removal? I'm almost certain this is a very recent change (or I'm too familar with various dialog implementations that I didn't catch this sooner when using this polyfill the past few years). 

Nonetheless, I've created a PR #90 in case it is missing without a good reason and it is in fact something that is to be expected with the dialog element.

**Comment by samthor** [comment]
Closed as not part of spec.
