### ISSUE TITLE
IE8 Support

### ISSUE THREAD

**Issue by wayferer** [GoogleChrome/dialog-polyfill#9]
Sorry if I missed this but are there any plans to support IE8?

**Comment by cvrebert** [comment]
[They dropped IE7 support](https://github.com/GoogleChrome/dialog-polyfill/commit/6e1b71cc3d8c9e690d226610aa7a89b370b84a6a) not too long ago, so they presumably support IE>=8 at this point. I'd likewise appreciate clarity on this though.

**Comment by samthor** [comment]
Closing in favour of #31

**Comment by cvrebert** [comment]
@samthor You didn't actually press the Close button..

**Comment by samthor** [comment]
Thanks.

Also, I'll note that the change you mention above actually drops IE8 support - IE8 doesn't support `rgba`. There might have been some confusion there.
