### ISSUE TITLE
Exposed to global even in CommonJS environment

### ISSUE THREAD

**Issue by niksy** [GoogleChrome/dialog-polyfill#93]
Is it necessary to expose dialog polyfill to `window` even when it’s used inside CommonJS environment (https://github.com/GoogleChrome/dialog-polyfill/blob/master/dialog-polyfill.js#L496)? Seems like it shouldn’t be.

**Comment by samthor** [comment]
This is historical: the global was added as part of the first, early commits, and users may rely on it.

Having said that, it could be done in an `} else {` branch after the CommonJS/AMD stuff. Send a PR! :)

**Comment by niksy** [comment]
Well, silly me. Opened a PR. :)
