### ISSUE TITLE
edge and firefox dialog not responding to input and submit

### ISSUE THREAD

**Issue by lepatlamass** [GoogleChrome/dialog-polyfill#99]
can't input text and submit form with edge and firefox 45 have already corrected the positioning but can't figure out what is wrong on the input and submit.please stuck in a project with mdl really need help in to this issue thanks.

**Comment by mkc188** [comment]
same issue here +1

**Comment by samthor** [comment]
Hey there, can you check out this repo and load this file in Firefox and Edge?

https://github.com/GoogleChrome/dialog-polyfill/blob/master/tests/form.html

In Firefox, which I've tested, I can focus on the `input` fine and submit the form. Can you provide sample code as to what's not working for you?

**Comment by madwill** [comment]
I have had the same problem. 

Somehow in firefox a "_dialog_overlay" gets over everything and prevent mouse input by capturing events.

Really have no idea what this does. But surprizingly if you remove it with simple 

._dialog_overlay{
    display:none;      
}

Then the whole thing works normally. Perhaps it has to do with this : 
https://github.com/GoogleChrome/dialog-polyfill/commit/7f8b3cc9bffdb21c5d474ad5a1fbd06cf9c37b55
Perhaps not.

Point is display none until further notice for me. 

Thank you all

**Comment by noopole** [comment]
I experienced the same beaviour because my dialog was place inside a div with a style with `{position:fixed}`, which make the dialog's z-index (100002) relative and therefore not recovering the `_dialog_overlay`.

**Comment by samthor** [comment]
Closing this as it's related to incorrect use of stacking context. We now warn if you're making a mistake, and also are more permissive, so incorrect usage might still work: #131
